### ISSUE TITLE
organize_football_files.php is missing

### ISSUE THREAD

**Issue by litch** [DarrenCook/h2o#3]
It's mentioned in the text  - on page 82, but I don't see it here.

**Comment by DarrenCook** [comment]
Thanks! I've just uploaded it: https://github.com/DarrenCook/h2o/commit/964b57df5bad69d90c3e1c67865173f6edc5f8f7

**Comment by litch** [comment]
Great - by the way, I really enjoyed working through the book. Learned a ton about ML and more about football than I thought I would. =)

**Comment by DarrenCook** [comment]
Thanks - if you get chance to post a review somewhere (Amazon, O'Reilly, social media) I'd really appreciate it.
